### PR TITLE
UI

### LINKED ISSUE #40: Create UI
- [x] Button for running fabric_nodes.launch.py
- [x] Button for config file path selection
- [x] Button for switching the env
- [x] Tables for showing the letency, bandwitdh, frequency, and loss count for each topic
- [x] Adjust readme and Doxygen for teaching the user how to operate the UI

### PR DESCRIPTION
**Pull request by ihkao**
Close #40 
In order to test the UI, run the following command:
`ros2 run fabric_gui fabric_gui_exe`  
  
There are stiil some works to do: 
Ploting figure to show histogram and lines of each topics. 
Design an UI format for building custom yamls.  

To avoid too many lines of code review, I prefer to merge this workable version first.

### CODE REVIEW

**Comment by LawrenceXu13467** [comment]
unable_to_pause
Tested working. However, sometimes I couldn't pause after launching, like the screenshot above.

**Comment by ihkao** [comment]
The screenshot suggests that you've paused and obtained the measurement result.  
You can only activate the pause button after pressing the launch button.  
There's a logic in place ensuring that the launch and pause buttons aren't both enabled simultaneously.

**Comment by LawrenceXu13467** [comment]
> The screenshot suggests that you've paused and obtained the measurement result. You can only activate the pause button after pressing the launch button. There's a logic in place ensuring that the launch and pause buttons aren't both enabled simultaneously.

unable_to_pause
Maybe this one? The pause is greyed out right after I hit launch.

**Comment by ihkao** [comment]
Can you provide your operation step by step for me to represent your issue?

**Comment by LawrenceXu13467** [comment]
> Please provide your operation step by step for me to represent your issue.

I've merged as of now. As last time we discussed, the above issue only exists because once we find an available dds, the launch button won't be greyed out for other unavailable dds even if we switch later.

**Pull request merged**
